/* main for guitar tuner project
 * implements AMDF autocorrelation to find pitch/frequency
 * code in "MCC Generated Files" folder is generated by MCC code configurator and
 * subject to microchip license see mcc.h
 */

#include "mcc_generated_files/mcc.h"
#include "tuner_defs.h"
#include "tuner_display.h"
#include "amdf.h"
#include "ssd1306_oled.h"


//global vars
samp_t sample_buff[SAMPLE_SIZE] = { 0 }; //samples from adc
enum tuner {SCAN,COLLECT,PROCESS,RESET,SELECT_MODE} tuner_state; //sampling states

//button options 0-5 for specifying specific string of 6-string guitar, 6 = attempt auto detect
uint8_t btn_sel = 6;

//function prototypes
adc_result_t ADC_read(void);
#ifdef RAW_SIGNAL_DEBUG
void print_array(uint16_t len, samp_t *arr);
#endif

/* Timer interrupt for adc sample frequency     
 */
void TMR0_Interrupt(void){
    static uint16_t idx;
    static uint16_t btn_delay_count;
    samp_t adc_val;
    
    //check button every x ticks. if button is pressed, change string select
    if (btn_delay_count >= BTN_DELAY){
        btn_delay_count = 0;
        if(IO_RC7_PORT == 0){
            btn_sel++;
            if(btn_sel >= 7)
                btn_sel = 0;                
            tuner_state = SELECT_MODE;
        }           
    } 
    btn_delay_count++;
    
    adc_val = (samp_t)ADC_read();
    
    // Wait for an initial signal amplitude before collecting samples
    if (tuner_state == SCAN && adc_val > TRIGGER_LEVEL)
        tuner_state = COLLECT;
    if (tuner_state == COLLECT){
        if(idx < SAMPLE_SIZE){
            adc_val = (samp_t)(adc_val - ADCOFFSET);//remove calculated dc offset
            //save new adc sample
            sample_buff[idx] = adc_val;
            idx++;
        }
        else{//process valid signal
            tuner_state = PROCESS;
        }
    }
    if (tuner_state == RESET){
        idx = 0;
        tuner_state = SCAN;
    }
}

/* read adc, using this rather than mcc's ADC_GetConversion(adc_channel_t channel)
 * function. Since this project is using one adc channel 
 * and doesn't switch the channel on/off, it doesn't need acq delay
 * 
 * Allow selecting adc bit resolution 1-16, this mcu is up to 10 bit resolution
 * support for sub 3 bit and above 10 bit is here just for implementing in a 
 * generalized form although pointless.
 * 
 * Assumes ADC result is left justified
 */
adc_result_t ADC_read(void){
    // Start the conversion
    ADCON0bits.GO_nDONE = 1;
    // Wait for the conversion to finish. ~30uS in this wait loop
    while (ADCON0bits.GO_nDONE);
    // Conversion finished, return the result
#if ADCBITS > 8
    return (((adc_result_t)(ADRESH << 8) + ADRESL)>>(16-ADCBITS));;
#else
    return ADRESH >> (8-ADCBITS); 
#endif
}

/* Print the sample array
 */
#ifdef RAW_SIGNAL_DEBUG
void print_array(uint16_t len, samp_t *arr){
    printf("raw_signal = [");
    for(uint16_t i = 0; i < len; i++ )
        if(i == len-1) // last item. no comma
            printf("%i",arr[i]);
        else
            printf("%i,",arr[i]);
    printf("]\n");
}
#endif


/*
                         Main application
 */
void main(void)
{
    static uint8_t t_min = T_MIN, t_max = T_MAX;
    // initialize the device
    SYSTEM_Initialize();

    // When using interrupts, you need to set the Global and Peripheral Interrupt Enable bits
    // Use the following macros to:

    // Enable the Global Interrupts
    INTERRUPT_GlobalInterruptEnable();

    // Enable the Peripheral Interrupts
    //INTERRUPT_PeripheralInterruptEnable();

    // Disable the Global Interrupts
    //INTERRUPT_GlobalInterruptDisable();

    // Disable the Peripheral Interrupts
    //INTERRUPT_PeripheralInterruptDisable();
    
    TMR0_SetInterruptHandler(TMR0_Interrupt);
    ADC_SelectChannel(channel_AN11);
    
#ifdef RAW_SIGNAL_DEBUG
    printf("adc offset: %d adc trigger: %d \n", ADCOFFSET, TRIGGER_LEVEL);
#endif  
    
    
    ssd1306_init();
    tuner_state = SELECT_MODE;

    while (1)
    {
        if(tuner_state == SELECT_MODE){
            INTERRUPT_GlobalInterruptDisable();
            tuner_state = RESET;
            switch(btn_sel){
                case 0:
                    t_min = FS/96;
                    t_max = T_MAX;
                    break;
                case 1:
                    t_min = FS/128;
                    t_max = FS/96;
                    break;
                case 2:
                    t_min = FS/171;
                    t_max = FS/128;
                    break;
                case 3:
                    t_min = FS/221;
                    t_max = FS/171;
                    break;
                case 4:
                    t_min = FS/280;
                    t_max = FS/221;
                    break;
                case 5:
                    t_min = T_MIN;
                    t_max = FS/280;
                    break;
                case 6:
                    t_min = T_MIN;
                    t_max = T_MAX;
                    break;
            }
            tuner_display_mode(btn_sel);
            INTERRUPT_GlobalInterruptEnable();
        }
        // process signal, pause interrupt, clear sample buffer, display frequency
        // then restart sample collecting
        if(tuner_state == PROCESS){            
            INTERRUPT_GlobalInterruptDisable();
            tuner_state = RESET;
        
            uint16_t f = amdf(SAMPLE_SIZE, sample_buff, FS,t_min,t_max);
            //printf("freq: %u.%u\n",(uint16_t)(f/10),(uint16_t)(f%10));
            tuner_display(f);            

            INTERRUPT_GlobalInterruptEnable();
        }
    }
}
/**
 End of File
*/
